version: "3.8"

networks:
  hazelcast-net:
    driver: bridge

services:
  hz1:
    image: hazelcast/hazelcast:5.3
    container_name: hz1
    networks:
      - hazelcast-net
    ports:
      - "5701:5701"
    environment:
      - HZ_CLUSTERNAME=dev
    volumes:
      - ./config/hazelcast.xml:/opt/hazelcast/config/hazelcast.xml
    command: ["hz", "start", "-c", "/opt/hazelcast/config/hazelcast.xml"]

  hz2:
    image: hazelcast/hazelcast:5.3
    container_name: hz2
    networks:
      - hazelcast-net
    ports:
      - "5702:5701"
    environment:
      - HZ_CLUSTERNAME=dev
    volumes:
      - ./config/hazelcast.xml:/opt/hazelcast/config/hazelcast.xml
    command: ["hz", "start", "-c", "/opt/hazelcast/config/hazelcast.xml"]

  hz3:
    image: hazelcast/hazelcast:5.3
    container_name: hz3
    networks:
      - hazelcast-net
    ports:
      - "5703:5701"
    environment:
      - HZ_CLUSTERNAME=dev
    volumes:
      - ./config/hazelcast.xml:/opt/hazelcast/config/hazelcast.xml
    command: ["hz", "start", "-c", "/opt/hazelcast/config/hazelcast.xml"]

  management-center:
    image: hazelcast/management-center:5.3
    container_name: hz-mc
    networks:
      - hazelcast-net
    ports:
      - "8080:8080"
    environment:
      - MC_DEFAULT_CLUSTER=dev
      - MC_DEFAULT_CLUSTER_MEMBERS=hz1:5701,hz2:5701,hz3:5701